### PR TITLE
A lot of changes regarding Ipfs ipns versioning and structure of how we store the services

### PR DESCRIPTION
**Pull request by simon991**
- A lot of restructuring regarding Versioning and the naming system IPNS. Some stuff still needs to be refactored as the structure of the data in IPFS is different now.
- Also I changed the structure of the service-detail-component so it can be easily reused in other components as a directive. 
- I extended the service-repository.service.ts
- I started to implement the myservices-component and the corresponding part in the service-repository.service.ts

An IPFS daemon has the following directory structure:
>services _(entry point for IPNS)_
    --> example_service1    _(the hash for this dir is now the one that represents the current version of the service)_
            -------> metadata.json   _(contains some metadata information such as prices, name, description, ...)_
             -------> swagger.json   _(contains a swagger description file that describes the REST API of that service)_
    --> example_service2
            -------> metadata.json
             -------> swagger.json
     --> ...
            --> ...
            --> ...

### CODE REVIEW

**Comment by cp2017** [comment]
@simon991 Plz rebase to master, so that you can get the changes to the drone.yml(.sig) file. Your branch is still on the old version; hence it does not run the CI pipeline.

**Comment by ChristianKniep** [comment]
When using `.drone.yml`, `.drone.yml.sig` and `test.sh` from the current master I got this:
```
[build:L146:122s] Chrome 53.0.2785 (Linux 0.0.0): Executed 13 of 18 SUCCESS (0 secs / 5.432 secs)
                  Chrome 53.0.2785 (Linux 0.0.0) IpfsService should create a connection to the locally running IPFS daemon with address /ip4/127.0.0.1/tcp/5001 FAILEDld:L148:122s]
[build:L149:122s] 	Failed: Cannot read property 'length' of null
[build:L150:122s] 	TypeError: Cannot read property 'length' of null
[build:L151:122s] 	    at webpack:///drone/src/src/app/services/ipfs/ipfs.service.ts:9:4365 <- src/test.ts:7471:4369
[build:L152:122s] 	    at f (src/assets/ipfs-api/dist/index.js:13719:25)
[build:L153:122s] 	    at res.once.pipe.err (src/assets/ipfs-api/dist/index.js:65626:7)
[build:L154:122s] 	    at ConcatStream.<anonymous> (src/assets/ipfs-api/dist/index.js:29161:43)
[build:L155:122s] 	    at ConcatStream.EventEmitter.emit (src/assets/ipfs-api/dist/index.js:2496:20)
[build:L156:122s] 	    at finishMaybe (src/assets/ipfs-api/dist/index.js:13336:14)
[build:L157:122s] 	    at afterWrite (src/assets/ipfs-api/dist/index.js:13222:3)
[build:L158:122s] 	    at afterTick (src/assets/ipfs-api/dist/index.js:2749:10)
[build:L159:122s] 	    at Item.run (src/assets/ipfs-api/dist/index.js:2164:14)
[build:L160:122s] 	    at drainQueue (src/assets/ipfs-api/dist/index.js:2134:42)
[build:L161:122s] Chrome 53.0.2785 (Linux 0.0.0): Executed 14 of 18 (1 FAILED) (0 secs / 5.639 secs)
[build:L162:122s] Chrome 53.0.2785 (Linux 0.0.0) IpfsService should create a connection to the locally running IPFS daemon with address /ip4/127.0.0.1/tcp/5001 FAILED
[build:L163:122s] 	Failed: Cannot read property 'length' of null
[build:L164:122s] 	TypeError: Cannot read property 'length' of null
[build:L165:122s] 	    at webpack:///drone/src/src/app/services/ipfs/ipfs.service.ts:9:4365 <- src/test.ts:7471:4369
[build:L166:122s] 	    at f (src/assets/ipfs-api/dist/index.js:13719:25)
[build:L167:122s] 	    at res.once.pipe.err (src/assets/ipfs-api/dist/index.js:65626:7)
[build:L168:122s] 	    at ConcatStream.<anonymous> (src/assets/ipfs-api/dist/index.js:29161:43)
[build:L169:122s] 	    at ConcatStream.EventEmitter.emit (src/assets/ipfs-api/dist/index.js:2496:20)
[build:L170:122s] 	    at finishMaybe (src/assets/ipfs-api/dist/index.js:13336:14)
[build:L171:122s] 	    at afterWrite (src/assets/ipfs-api/dist/index.js:13222:3)
[build:L172:122s] 	    at afterTick (src/assets/ipfs-api/dist/index.js:2749:10)
[build:L173:122s] 	    at Item.run (src/assets/ipfs-api/dist/index.js:2164:14)
                  LOG: 'My IPFS node id is: ', 'QmedhUJ3YWx1yqoAEDcuRMwNPZYmDwdYSTKHvm5fzR6z43'
[build:L176:122s] Chrome 53.0.2785 (Linux 0.0.0): Executed 14 of 18 (1 FAILED) (0 secs / 5.639 secs)
                  Chrome 53.0.2785 (Linux 0.0.0) IpfsService should put a value to IPFS FAILED
[build:L179:122s] 	Failed: Cannot read property 'length' of null
[build:L180:122s] 	TypeError: Cannot read property 'length' of null
[build:L181:122s] 	    at webpack:///drone/src/src/app/services/ipfs/ipfs.service.ts:9:4365 <- src/test.ts:7471:4369
[build:L182:122s] 	    at f (src/assets/ipfs-api/dist/index.js:13719:25)
[build:L183:122s] 	    at res.once.pipe.err (src/assets/ipfs-api/dist/index.js:65626:7)
[build:L184:122s] 	    at ConcatStream.<anonymous> (src/assets/ipfs-api/dist/index.js:29161:43)
[build:L185:122s] 	    at ConcatStream.EventEmitter.emit (src/assets/ipfs-api/dist/index.js:2496:20)
[build:L186:122s] 	    at finishMaybe (src/assets/ipfs-api/dist/index.js:13336:14)
[build:L187:122s] 	    at afterWrite (src/assets/ipfs-api/dist/index.js:13222:3)
[build:L188:122s] 	    at afterTick (src/assets/ipfs-api/dist/index.js:2749:10)
[build:L189:122s] 	    at Item.run (src/assets/ipfs-api/dist/index.js:2164:14)
[build:L190:122s] 	    at drainQueue (src/assets/ipfs-api/dist/index.js:2134:42)
[build:L191:122s] Chrome 53.0.2785 (Linux 0.0.0): Executed 15 of 18 (2 FAILED) (0 secs / 5.706 secs)
[build:L192:122s] Chrome 53.0.2785 (Linux 0.0.0) IpfsService should put a value to IPFS FAILED
[build:L193:122s] 	Failed: Cannot read property 'length' of null
[build:L194:122s] 	TypeError: Cannot read property 'length' of null
[build:L195:122s] 	    at webpack:///drone/src/src/app/services/ipfs/ipfs.service.ts:9:4365 <- src/test.ts:7471:4369
[build:L196:122s] 	    at f (src/assets/ipfs-api/dist/index.js:13719:25)
[build:L197:122s] 	    at res.once.pipe.err (src/assets/ipfs-api/dist/index.js:65626:7)
[build:L198:122s] 	    at ConcatStream.<anonymous> (src/assets/ipfs-api/dist/index.js:29161:43)
[build:L199:122s] 	    at ConcatStream.EventEmitter.emit (src/assets/ipfs-api/dist/index.js:2496:20)
[build:L200:122s] 	    at finishMaybe (src/assets/ipfs-api/dist/index.js:13336:14)
[build:L201:122s] 	    at afterWrite (src/assets/ipfs-api/dist/index.js:13222:3)
[build:L202:122s] 	    at afterTick (src/assets/ipfs-api/dist/index.js:2749:10)
[build:L203:122s] 	    at Item.run (src/assets/ipfs-api/dist/index.js:2164:14)
                  LOG: 'My IPFS node id is: ', 'QmedhUJ3YWx1yqoAEDcuRMwNPZYmDwdYSTKHvm5fzR6z43'
[build:L206:122s] Chrome 53.0.2785 (Linux 0.0.0): Executed 15 of 18 (2 FAILED) (0 secs / 5.706 secs)
                  Chrome 53.0.2785 (Linux 0.0.0) IpfsService should put a value to IPFS and then get the same value back FAILED
[build:L209:122s] 	Failed: Cannot read property 'length' of null
[build:L210:122s] 	TypeError: Cannot read property 'length' of null
[build:L211:122s] 	    at webpack:///drone/src/src/app/services/ipfs/ipfs.service.ts:9:4365 <- src/test.ts:7471:4369
[build:L212:122s] 	    at f (src/assets/ipfs-api/dist/index.js:13719:25)
[build:L213:122s] 	    at res.once.pipe.err (src/assets/ipfs-api/dist/index.js:65626:7)
[build:L214:122s] 	    at ConcatStream.<anonymous> (src/assets/ipfs-api/dist/index.js:29161:43)
[build:L215:122s] 	    at ConcatStream.EventEmitter.emit (src/assets/ipfs-api/dist/index.js:2496:20)
[build:L216:122s] 	    at finishMaybe (src/assets/ipfs-api/dist/index.js:13336:14)
[build:L217:122s] 	    at afterWrite (src/assets/ipfs-api/dist/index.js:13222:3)
[build:L218:122s] 	    at afterTick (src/assets/ipfs-api/dist/index.js:2749:10)
[build:L219:122s] 	    at Item.run (src/assets/ipfs-api/dist/index.js:2164:14)
[build:L220:122s] 	    at drainQueue (src/assets/ipfs-api/dist/index.js:2134:42)
[build:L221:122s] Chrome 53.0.2785 (Linux 0.0.0): Executed 16 of 18 (3 FAILED) (0 secs / 5.756 secs)
[build:L222:122s] Chrome 53.0.2785 (Linux 0.0.0) IpfsService should put a value to IPFS and then get the same value back FAILED
[build:L223:122s] 	Failed: Cannot read property 'length' of null
[build:L224:122s] 	TypeError: Cannot read property 'length' of null
[build:L225:122s] 	    at webpack:///drone/src/src/app/services/ipfs/ipfs.service.ts:9:4365 <- src/test.ts:7471:4369
[build:L226:122s] 	    at f (src/assets/ipfs-api/dist/index.js:13719:25)
[build:L227:122s] 	    at res.once.pipe.err (src/assets/ipfs-api/dist/index.js:65626:7)
[build:L228:122s] 	    at ConcatStream.<anonymous> (src/assets/ipfs-api/dist/index.js:29161:43)
[build:L229:122s] 	    at ConcatStream.EventEmitter.emit (src/assets/ipfs-api/dist/index.js:2496:20)
[build:L230:122s] 	    at finishMaybe (src/assets/ipfs-api/dist/index.js:13336:14)
[build:L231:122s] 	    at afterWrite (src/assets/ipfs-api/dist/index.js:13222:3)
[build:L232:122s] 	    at afterTick (src/assets/ipfs-api/dist/index.js:2749:10)
[build:L233:122s] 	    at Item.run (src/assets/ipfs-api/dist/index.js:2164:14)
                  Chrome 53.0.2785 (Linux 0.0.0): Executed 18 of 18 (3 FAILED) (6.101 secs / 5.997 secs)
[build:L238:122s] 09 01 2017 09:08:19.724:DEBUG [reporter.remap-istanbul]: Writing coverage to coverage
```

**Comment by simon991** [comment]
@ChristianKniep I found the error =) . It was my fault, sorry!!!

**Comment by ChristianKniep** [comment]
As the test are grren now: LGTM

**Pull request merged**
